
interface _GlobalComponents {
      'UiButton': typeof import("../client/components/ui/button/Button.vue")['default']
    'UiCard': typeof import("../client/components/ui/card/Card.vue")['default']
    'UiCardContent': typeof import("../client/components/ui/card/CardContent.vue")['default']
    'UiCardDescription': typeof import("../client/components/ui/card/CardDescription.vue")['default']
    'UiCardFooter': typeof import("../client/components/ui/card/CardFooter.vue")['default']
    'UiCardHeader': typeof import("../client/components/ui/card/CardHeader.vue")['default']
    'UiCardTitle': typeof import("../client/components/ui/card/CardTitle.vue")['default']
    'UiBarChart': typeof import("../client/components/ui/chart-bar/BarChart.vue")['default']
    'UiChartCrosshair': typeof import("../client/components/ui/chart/ChartCrosshair.vue")['default']
    'UiChartLegend': typeof import("../client/components/ui/chart/ChartLegend.vue")['default']
    'UiChartSingleTooltip': typeof import("../client/components/ui/chart/ChartSingleTooltip.vue")['default']
    'UiChartTooltip': typeof import("../client/components/ui/chart/ChartTooltip.vue")['default']
    'UiCheckbox': typeof import("../client/components/ui/checkbox/Checkbox.vue")['default']
    'UiDrawer': typeof import("../client/components/ui/drawer/Drawer.vue")['default']
    'UiDrawerContent': typeof import("../client/components/ui/drawer/DrawerContent.vue")['default']
    'UiDrawerDescription': typeof import("../client/components/ui/drawer/DrawerDescription.vue")['default']
    'UiDrawerFooter': typeof import("../client/components/ui/drawer/DrawerFooter.vue")['default']
    'UiDrawerHeader': typeof import("../client/components/ui/drawer/DrawerHeader.vue")['default']
    'UiDrawerOverlay': typeof import("../client/components/ui/drawer/DrawerOverlay.vue")['default']
    'UiDrawerTitle': typeof import("../client/components/ui/drawer/DrawerTitle.vue")['default']
    'UiDropdownMenu': typeof import("../client/components/ui/dropdown-menu/DropdownMenu.vue")['default']
    'UiDropdownMenuCheckboxItem': typeof import("../client/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
    'UiDropdownMenuContent': typeof import("../client/components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
    'UiDropdownMenuGroup': typeof import("../client/components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
    'UiDropdownMenuItem': typeof import("../client/components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
    'UiDropdownMenuLabel': typeof import("../client/components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
    'UiDropdownMenuRadioGroup': typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
    'UiDropdownMenuRadioItem': typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
    'UiDropdownMenuSeparator': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
    'UiDropdownMenuShortcut': typeof import("../client/components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
    'UiDropdownMenuSub': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
    'UiDropdownMenuSubContent': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
    'UiDropdownMenuSubTrigger': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
    'UiDropdownMenuTrigger': typeof import("../client/components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
    'UiInput': typeof import("../client/components/ui/input/Input.vue")['default']
    'UiLabel': typeof import("../client/components/ui/label/Label.vue")['default']
    'UiTable': typeof import("../client/components/ui/table/Table.vue")['default']
    'UiTableBody': typeof import("../client/components/ui/table/TableBody.vue")['default']
    'UiTableCaption': typeof import("../client/components/ui/table/TableCaption.vue")['default']
    'UiTableCell': typeof import("../client/components/ui/table/TableCell.vue")['default']
    'UiTableEmpty': typeof import("../client/components/ui/table/TableEmpty.vue")['default']
    'UiTableFooter': typeof import("../client/components/ui/table/TableFooter.vue")['default']
    'UiTableHead': typeof import("../client/components/ui/table/TableHead.vue")['default']
    'UiTableHeader': typeof import("../client/components/ui/table/TableHeader.vue")['default']
    'UiTableRow': typeof import("../client/components/ui/table/TableRow.vue")['default']
    'UiTooltip': typeof import("../client/components/ui/tooltip/Tooltip.vue")['default']
    'UiTooltipContent': typeof import("../client/components/ui/tooltip/TooltipContent.vue")['default']
    'UiTooltipProvider': typeof import("../client/components/ui/tooltip/TooltipProvider.vue")['default']
    'UiTooltipTrigger': typeof import("../client/components/ui/tooltip/TooltipTrigger.vue")['default']
    'AppHeader': typeof import("../client/components/AppHeader.vue")['default']
    'AppSidebar': typeof import("../client/components/AppSidebar.vue")['default']
    'AuthCard': typeof import("../client/components/AuthCard.vue")['default']
    'AuthSessionStatus': typeof import("../client/components/AuthSessionStatus.vue")['default']
    'Button': typeof import("../client/components/Button.vue")['default']
    'Chart': typeof import("../client/components/Chart/index.vue")['default']
    'DisplayMode': typeof import("../client/components/DisplayMode.vue")['default']
    'DropdownButton': typeof import("../client/components/Dropdown/Button.vue")['default']
    'Dropdown': typeof import("../client/components/Dropdown/Dropdown.vue")['default']
    'DropdownLink': typeof import("../client/components/Dropdown/Link.vue")['default']
    'FlashMessages': typeof import("../client/components/FlashMessages.vue")['default']
    'Input': typeof import("../client/components/Input.vue")['default']
    'Label': typeof import("../client/components/Label.vue")['default']
    'Logo': typeof import("../client/components/Logo.vue")['default']
    'MenuLogo': typeof import("../client/components/MenuLogo.vue")['default']
    'PosCartAction': typeof import("../client/components/pos/CartAction.vue")['default']
    'PosCartHeader': typeof import("../client/components/pos/CartHeader.vue")['default']
    'PosCartScanner': typeof import("../client/components/pos/CartScanner.vue")['default']
    'PosCartTable': typeof import("../client/components/pos/CartTable.vue")['default']
    'PosCartTotal': typeof import("../client/components/pos/CartTotal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'UiPagination': typeof import("radix-vue")['PaginationRoot']
    'UiPaginationList': typeof import("radix-vue")['PaginationList']
    'UiPaginationListItem': typeof import("radix-vue")['PaginationListItem']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyUiButton': typeof import("../client/components/ui/button/Button.vue")['default']
    'LazyUiCard': typeof import("../client/components/ui/card/Card.vue")['default']
    'LazyUiCardContent': typeof import("../client/components/ui/card/CardContent.vue")['default']
    'LazyUiCardDescription': typeof import("../client/components/ui/card/CardDescription.vue")['default']
    'LazyUiCardFooter': typeof import("../client/components/ui/card/CardFooter.vue")['default']
    'LazyUiCardHeader': typeof import("../client/components/ui/card/CardHeader.vue")['default']
    'LazyUiCardTitle': typeof import("../client/components/ui/card/CardTitle.vue")['default']
    'LazyUiBarChart': typeof import("../client/components/ui/chart-bar/BarChart.vue")['default']
    'LazyUiChartCrosshair': typeof import("../client/components/ui/chart/ChartCrosshair.vue")['default']
    'LazyUiChartLegend': typeof import("../client/components/ui/chart/ChartLegend.vue")['default']
    'LazyUiChartSingleTooltip': typeof import("../client/components/ui/chart/ChartSingleTooltip.vue")['default']
    'LazyUiChartTooltip': typeof import("../client/components/ui/chart/ChartTooltip.vue")['default']
    'LazyUiCheckbox': typeof import("../client/components/ui/checkbox/Checkbox.vue")['default']
    'LazyUiDrawer': typeof import("../client/components/ui/drawer/Drawer.vue")['default']
    'LazyUiDrawerContent': typeof import("../client/components/ui/drawer/DrawerContent.vue")['default']
    'LazyUiDrawerDescription': typeof import("../client/components/ui/drawer/DrawerDescription.vue")['default']
    'LazyUiDrawerFooter': typeof import("../client/components/ui/drawer/DrawerFooter.vue")['default']
    'LazyUiDrawerHeader': typeof import("../client/components/ui/drawer/DrawerHeader.vue")['default']
    'LazyUiDrawerOverlay': typeof import("../client/components/ui/drawer/DrawerOverlay.vue")['default']
    'LazyUiDrawerTitle': typeof import("../client/components/ui/drawer/DrawerTitle.vue")['default']
    'LazyUiDropdownMenu': typeof import("../client/components/ui/dropdown-menu/DropdownMenu.vue")['default']
    'LazyUiDropdownMenuCheckboxItem': typeof import("../client/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
    'LazyUiDropdownMenuContent': typeof import("../client/components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
    'LazyUiDropdownMenuGroup': typeof import("../client/components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
    'LazyUiDropdownMenuItem': typeof import("../client/components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
    'LazyUiDropdownMenuLabel': typeof import("../client/components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
    'LazyUiDropdownMenuRadioGroup': typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
    'LazyUiDropdownMenuRadioItem': typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
    'LazyUiDropdownMenuSeparator': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
    'LazyUiDropdownMenuShortcut': typeof import("../client/components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
    'LazyUiDropdownMenuSub': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
    'LazyUiDropdownMenuSubContent': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
    'LazyUiDropdownMenuSubTrigger': typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
    'LazyUiDropdownMenuTrigger': typeof import("../client/components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
    'LazyUiInput': typeof import("../client/components/ui/input/Input.vue")['default']
    'LazyUiLabel': typeof import("../client/components/ui/label/Label.vue")['default']
    'LazyUiTable': typeof import("../client/components/ui/table/Table.vue")['default']
    'LazyUiTableBody': typeof import("../client/components/ui/table/TableBody.vue")['default']
    'LazyUiTableCaption': typeof import("../client/components/ui/table/TableCaption.vue")['default']
    'LazyUiTableCell': typeof import("../client/components/ui/table/TableCell.vue")['default']
    'LazyUiTableEmpty': typeof import("../client/components/ui/table/TableEmpty.vue")['default']
    'LazyUiTableFooter': typeof import("../client/components/ui/table/TableFooter.vue")['default']
    'LazyUiTableHead': typeof import("../client/components/ui/table/TableHead.vue")['default']
    'LazyUiTableHeader': typeof import("../client/components/ui/table/TableHeader.vue")['default']
    'LazyUiTableRow': typeof import("../client/components/ui/table/TableRow.vue")['default']
    'LazyUiTooltip': typeof import("../client/components/ui/tooltip/Tooltip.vue")['default']
    'LazyUiTooltipContent': typeof import("../client/components/ui/tooltip/TooltipContent.vue")['default']
    'LazyUiTooltipProvider': typeof import("../client/components/ui/tooltip/TooltipProvider.vue")['default']
    'LazyUiTooltipTrigger': typeof import("../client/components/ui/tooltip/TooltipTrigger.vue")['default']
    'LazyAppHeader': typeof import("../client/components/AppHeader.vue")['default']
    'LazyAppSidebar': typeof import("../client/components/AppSidebar.vue")['default']
    'LazyAuthCard': typeof import("../client/components/AuthCard.vue")['default']
    'LazyAuthSessionStatus': typeof import("../client/components/AuthSessionStatus.vue")['default']
    'LazyButton': typeof import("../client/components/Button.vue")['default']
    'LazyChart': typeof import("../client/components/Chart/index.vue")['default']
    'LazyDisplayMode': typeof import("../client/components/DisplayMode.vue")['default']
    'LazyDropdownButton': typeof import("../client/components/Dropdown/Button.vue")['default']
    'LazyDropdown': typeof import("../client/components/Dropdown/Dropdown.vue")['default']
    'LazyDropdownLink': typeof import("../client/components/Dropdown/Link.vue")['default']
    'LazyFlashMessages': typeof import("../client/components/FlashMessages.vue")['default']
    'LazyInput': typeof import("../client/components/Input.vue")['default']
    'LazyLabel': typeof import("../client/components/Label.vue")['default']
    'LazyLogo': typeof import("../client/components/Logo.vue")['default']
    'LazyMenuLogo': typeof import("../client/components/MenuLogo.vue")['default']
    'LazyPosCartAction': typeof import("../client/components/pos/CartAction.vue")['default']
    'LazyPosCartHeader': typeof import("../client/components/pos/CartHeader.vue")['default']
    'LazyPosCartScanner': typeof import("../client/components/pos/CartScanner.vue")['default']
    'LazyPosCartTable': typeof import("../client/components/pos/CartTable.vue")['default']
    'LazyPosCartTotal': typeof import("../client/components/pos/CartTotal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyUiPagination': typeof import("radix-vue")['PaginationRoot']
    'LazyUiPaginationList': typeof import("radix-vue")['PaginationList']
    'LazyUiPaginationListItem': typeof import("radix-vue")['PaginationListItem']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const UiButton: typeof import("../client/components/ui/button/Button.vue")['default']
export const UiCard: typeof import("../client/components/ui/card/Card.vue")['default']
export const UiCardContent: typeof import("../client/components/ui/card/CardContent.vue")['default']
export const UiCardDescription: typeof import("../client/components/ui/card/CardDescription.vue")['default']
export const UiCardFooter: typeof import("../client/components/ui/card/CardFooter.vue")['default']
export const UiCardHeader: typeof import("../client/components/ui/card/CardHeader.vue")['default']
export const UiCardTitle: typeof import("../client/components/ui/card/CardTitle.vue")['default']
export const UiBarChart: typeof import("../client/components/ui/chart-bar/BarChart.vue")['default']
export const UiChartCrosshair: typeof import("../client/components/ui/chart/ChartCrosshair.vue")['default']
export const UiChartLegend: typeof import("../client/components/ui/chart/ChartLegend.vue")['default']
export const UiChartSingleTooltip: typeof import("../client/components/ui/chart/ChartSingleTooltip.vue")['default']
export const UiChartTooltip: typeof import("../client/components/ui/chart/ChartTooltip.vue")['default']
export const UiCheckbox: typeof import("../client/components/ui/checkbox/Checkbox.vue")['default']
export const UiDrawer: typeof import("../client/components/ui/drawer/Drawer.vue")['default']
export const UiDrawerContent: typeof import("../client/components/ui/drawer/DrawerContent.vue")['default']
export const UiDrawerDescription: typeof import("../client/components/ui/drawer/DrawerDescription.vue")['default']
export const UiDrawerFooter: typeof import("../client/components/ui/drawer/DrawerFooter.vue")['default']
export const UiDrawerHeader: typeof import("../client/components/ui/drawer/DrawerHeader.vue")['default']
export const UiDrawerOverlay: typeof import("../client/components/ui/drawer/DrawerOverlay.vue")['default']
export const UiDrawerTitle: typeof import("../client/components/ui/drawer/DrawerTitle.vue")['default']
export const UiDropdownMenu: typeof import("../client/components/ui/dropdown-menu/DropdownMenu.vue")['default']
export const UiDropdownMenuCheckboxItem: typeof import("../client/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
export const UiDropdownMenuContent: typeof import("../client/components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
export const UiDropdownMenuGroup: typeof import("../client/components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
export const UiDropdownMenuItem: typeof import("../client/components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
export const UiDropdownMenuLabel: typeof import("../client/components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
export const UiDropdownMenuRadioGroup: typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
export const UiDropdownMenuRadioItem: typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
export const UiDropdownMenuSeparator: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
export const UiDropdownMenuShortcut: typeof import("../client/components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
export const UiDropdownMenuSub: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
export const UiDropdownMenuSubContent: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
export const UiDropdownMenuSubTrigger: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
export const UiDropdownMenuTrigger: typeof import("../client/components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
export const UiInput: typeof import("../client/components/ui/input/Input.vue")['default']
export const UiLabel: typeof import("../client/components/ui/label/Label.vue")['default']
export const UiTable: typeof import("../client/components/ui/table/Table.vue")['default']
export const UiTableBody: typeof import("../client/components/ui/table/TableBody.vue")['default']
export const UiTableCaption: typeof import("../client/components/ui/table/TableCaption.vue")['default']
export const UiTableCell: typeof import("../client/components/ui/table/TableCell.vue")['default']
export const UiTableEmpty: typeof import("../client/components/ui/table/TableEmpty.vue")['default']
export const UiTableFooter: typeof import("../client/components/ui/table/TableFooter.vue")['default']
export const UiTableHead: typeof import("../client/components/ui/table/TableHead.vue")['default']
export const UiTableHeader: typeof import("../client/components/ui/table/TableHeader.vue")['default']
export const UiTableRow: typeof import("../client/components/ui/table/TableRow.vue")['default']
export const UiTooltip: typeof import("../client/components/ui/tooltip/Tooltip.vue")['default']
export const UiTooltipContent: typeof import("../client/components/ui/tooltip/TooltipContent.vue")['default']
export const UiTooltipProvider: typeof import("../client/components/ui/tooltip/TooltipProvider.vue")['default']
export const UiTooltipTrigger: typeof import("../client/components/ui/tooltip/TooltipTrigger.vue")['default']
export const AppHeader: typeof import("../client/components/AppHeader.vue")['default']
export const AppSidebar: typeof import("../client/components/AppSidebar.vue")['default']
export const AuthCard: typeof import("../client/components/AuthCard.vue")['default']
export const AuthSessionStatus: typeof import("../client/components/AuthSessionStatus.vue")['default']
export const Button: typeof import("../client/components/Button.vue")['default']
export const Chart: typeof import("../client/components/Chart/index.vue")['default']
export const DisplayMode: typeof import("../client/components/DisplayMode.vue")['default']
export const DropdownButton: typeof import("../client/components/Dropdown/Button.vue")['default']
export const Dropdown: typeof import("../client/components/Dropdown/Dropdown.vue")['default']
export const DropdownLink: typeof import("../client/components/Dropdown/Link.vue")['default']
export const FlashMessages: typeof import("../client/components/FlashMessages.vue")['default']
export const Input: typeof import("../client/components/Input.vue")['default']
export const Label: typeof import("../client/components/Label.vue")['default']
export const Logo: typeof import("../client/components/Logo.vue")['default']
export const MenuLogo: typeof import("../client/components/MenuLogo.vue")['default']
export const PosCartAction: typeof import("../client/components/pos/CartAction.vue")['default']
export const PosCartHeader: typeof import("../client/components/pos/CartHeader.vue")['default']
export const PosCartScanner: typeof import("../client/components/pos/CartScanner.vue")['default']
export const PosCartTable: typeof import("../client/components/pos/CartTable.vue")['default']
export const PosCartTotal: typeof import("../client/components/pos/CartTotal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const UiPagination: typeof import("radix-vue")['PaginationRoot']
export const UiPaginationList: typeof import("radix-vue")['PaginationList']
export const UiPaginationListItem: typeof import("radix-vue")['PaginationListItem']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyUiButton: typeof import("../client/components/ui/button/Button.vue")['default']
export const LazyUiCard: typeof import("../client/components/ui/card/Card.vue")['default']
export const LazyUiCardContent: typeof import("../client/components/ui/card/CardContent.vue")['default']
export const LazyUiCardDescription: typeof import("../client/components/ui/card/CardDescription.vue")['default']
export const LazyUiCardFooter: typeof import("../client/components/ui/card/CardFooter.vue")['default']
export const LazyUiCardHeader: typeof import("../client/components/ui/card/CardHeader.vue")['default']
export const LazyUiCardTitle: typeof import("../client/components/ui/card/CardTitle.vue")['default']
export const LazyUiBarChart: typeof import("../client/components/ui/chart-bar/BarChart.vue")['default']
export const LazyUiChartCrosshair: typeof import("../client/components/ui/chart/ChartCrosshair.vue")['default']
export const LazyUiChartLegend: typeof import("../client/components/ui/chart/ChartLegend.vue")['default']
export const LazyUiChartSingleTooltip: typeof import("../client/components/ui/chart/ChartSingleTooltip.vue")['default']
export const LazyUiChartTooltip: typeof import("../client/components/ui/chart/ChartTooltip.vue")['default']
export const LazyUiCheckbox: typeof import("../client/components/ui/checkbox/Checkbox.vue")['default']
export const LazyUiDrawer: typeof import("../client/components/ui/drawer/Drawer.vue")['default']
export const LazyUiDrawerContent: typeof import("../client/components/ui/drawer/DrawerContent.vue")['default']
export const LazyUiDrawerDescription: typeof import("../client/components/ui/drawer/DrawerDescription.vue")['default']
export const LazyUiDrawerFooter: typeof import("../client/components/ui/drawer/DrawerFooter.vue")['default']
export const LazyUiDrawerHeader: typeof import("../client/components/ui/drawer/DrawerHeader.vue")['default']
export const LazyUiDrawerOverlay: typeof import("../client/components/ui/drawer/DrawerOverlay.vue")['default']
export const LazyUiDrawerTitle: typeof import("../client/components/ui/drawer/DrawerTitle.vue")['default']
export const LazyUiDropdownMenu: typeof import("../client/components/ui/dropdown-menu/DropdownMenu.vue")['default']
export const LazyUiDropdownMenuCheckboxItem: typeof import("../client/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
export const LazyUiDropdownMenuContent: typeof import("../client/components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
export const LazyUiDropdownMenuGroup: typeof import("../client/components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
export const LazyUiDropdownMenuItem: typeof import("../client/components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
export const LazyUiDropdownMenuLabel: typeof import("../client/components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
export const LazyUiDropdownMenuRadioGroup: typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
export const LazyUiDropdownMenuRadioItem: typeof import("../client/components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
export const LazyUiDropdownMenuSeparator: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
export const LazyUiDropdownMenuShortcut: typeof import("../client/components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
export const LazyUiDropdownMenuSub: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
export const LazyUiDropdownMenuSubContent: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
export const LazyUiDropdownMenuSubTrigger: typeof import("../client/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
export const LazyUiDropdownMenuTrigger: typeof import("../client/components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
export const LazyUiInput: typeof import("../client/components/ui/input/Input.vue")['default']
export const LazyUiLabel: typeof import("../client/components/ui/label/Label.vue")['default']
export const LazyUiTable: typeof import("../client/components/ui/table/Table.vue")['default']
export const LazyUiTableBody: typeof import("../client/components/ui/table/TableBody.vue")['default']
export const LazyUiTableCaption: typeof import("../client/components/ui/table/TableCaption.vue")['default']
export const LazyUiTableCell: typeof import("../client/components/ui/table/TableCell.vue")['default']
export const LazyUiTableEmpty: typeof import("../client/components/ui/table/TableEmpty.vue")['default']
export const LazyUiTableFooter: typeof import("../client/components/ui/table/TableFooter.vue")['default']
export const LazyUiTableHead: typeof import("../client/components/ui/table/TableHead.vue")['default']
export const LazyUiTableHeader: typeof import("../client/components/ui/table/TableHeader.vue")['default']
export const LazyUiTableRow: typeof import("../client/components/ui/table/TableRow.vue")['default']
export const LazyUiTooltip: typeof import("../client/components/ui/tooltip/Tooltip.vue")['default']
export const LazyUiTooltipContent: typeof import("../client/components/ui/tooltip/TooltipContent.vue")['default']
export const LazyUiTooltipProvider: typeof import("../client/components/ui/tooltip/TooltipProvider.vue")['default']
export const LazyUiTooltipTrigger: typeof import("../client/components/ui/tooltip/TooltipTrigger.vue")['default']
export const LazyAppHeader: typeof import("../client/components/AppHeader.vue")['default']
export const LazyAppSidebar: typeof import("../client/components/AppSidebar.vue")['default']
export const LazyAuthCard: typeof import("../client/components/AuthCard.vue")['default']
export const LazyAuthSessionStatus: typeof import("../client/components/AuthSessionStatus.vue")['default']
export const LazyButton: typeof import("../client/components/Button.vue")['default']
export const LazyChart: typeof import("../client/components/Chart/index.vue")['default']
export const LazyDisplayMode: typeof import("../client/components/DisplayMode.vue")['default']
export const LazyDropdownButton: typeof import("../client/components/Dropdown/Button.vue")['default']
export const LazyDropdown: typeof import("../client/components/Dropdown/Dropdown.vue")['default']
export const LazyDropdownLink: typeof import("../client/components/Dropdown/Link.vue")['default']
export const LazyFlashMessages: typeof import("../client/components/FlashMessages.vue")['default']
export const LazyInput: typeof import("../client/components/Input.vue")['default']
export const LazyLabel: typeof import("../client/components/Label.vue")['default']
export const LazyLogo: typeof import("../client/components/Logo.vue")['default']
export const LazyMenuLogo: typeof import("../client/components/MenuLogo.vue")['default']
export const LazyPosCartAction: typeof import("../client/components/pos/CartAction.vue")['default']
export const LazyPosCartHeader: typeof import("../client/components/pos/CartHeader.vue")['default']
export const LazyPosCartScanner: typeof import("../client/components/pos/CartScanner.vue")['default']
export const LazyPosCartTable: typeof import("../client/components/pos/CartTable.vue")['default']
export const LazyPosCartTotal: typeof import("../client/components/pos/CartTotal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyUiPagination: typeof import("radix-vue")['PaginationRoot']
export const LazyUiPaginationList: typeof import("radix-vue")['PaginationList']
export const LazyUiPaginationListItem: typeof import("radix-vue")['PaginationListItem']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
