// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/26/2024, 3:57:20 PM
const configMerger = require("/home/mak/Documents/POS/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/mak/Documents/POS/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/plugins/**/*.{js,ts,mjs}","/home/mak/Documents/POS/client/utils\", ./stores/**/*.{js,ts,mjs}","/home/mak/Documents/POS/client/composables/*/*.{ts,js}/**/*.{js,ts,mjs}","/home/mak/Documents/POS/client/composables/**/*.{js,ts,mjs}","/home/mak/Documents/POS/client/utils/**/*.{js,ts,mjs}","/home/mak/Documents/POS/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/mak/Documents/POS/client/app.config.{js,ts,mjs}"] }));

module.exports = config
